### ISSUE TITLE
Backtransform Outcome in Effect_Plot

### ISSUE THREAD

**Issue by abadgerw** [jacob-long/jtools#151]
I am working with the attached dataset: 
[Test.csv](https://github.com/jacob-long/jtools/files/15279057/Test.csv)

I am running the following model:

```
library(ggeffects)
library(jtools)

df<-read.csv("Test.csv",header=T,row.names=1)

model<-lm(log(Molecule) ~ Volume + Pred1 + Pred2 + Pred3, data=df)

```

I tried plotting the results using effect_plot:

```
effect_plot(model,pred="Volume",interval=TRUE,plot.points = TRUE,data=df)

```

![Effect_Plot](https://github.com/jacob-long/jtools/assets/90532108/b9ff8db7-b853-4282-ab90-d6ad05e87f0d)

However, I can't seem to get the plot to display the native backtransformed y-axis, only the logged values. Any way that can be done?

I know the ggeffects package can display the backtransformed y-axis but it seems to have issues plotting the points as your package can (see issue here: https://github.com/strengejacke/ggeffects/issues/522)

**Comment by jacob-long** [comment]
I think the best answer for now is that there's no **simple** way to achieve this --- I worked to make sure that the function doesn't break when there are transformations in the formula, but the package isn't currently setup to make it easy for the user to choose whether a formula-transformed outcome can be plotted on the original vs. transformed scale. 

You're not left totally high and dry, though, since we can at least get you the raw data to feed to `ggplot2` via the `make_predictions()` function.

```r
preds <- make_predictions(model, pred = "Volume", interval = TRUE, plot.points = TRUE, data = df)
```

Note that `preds` will have a column called `` `log(Molecule)` `` which contains the model predictions as well as another column called `Molecule` that has been automatically filled with the mean of `Molecule` as if it's a control variable. So we will replace that with back-transformed model predictions like so:

```r
preds$Molecule <- exp(preds$`log(Molecule)`)
```

With that, we can start plotting the regression line:

```r
plot <- ggplot(preds, aes(x = Volume, y = Molecule)) + geom_path() + theme_nice()
```

![image](https://github.com/user-attachments/assets/f2ec3d75-b0db-41c3-9d6f-3b70c955c691)


Then we can add the original data back...

```r
plot + geom_point(data = df)
```

![image](https://github.com/user-attachments/assets/6da32f76-6265-447e-a568-45a00ff0173b)

Now one issue as far as the intelligibility of the plot with your data is you have one enormous outlier (Molecule = 5611956) and one other observation that stretches the axis a good bit (Molecule = 883766). So you could choose to squeeze the axis to exclude them, although I don't know if that will be ultimately misleading:

```r
plot + geom_point(data = df) + ylim(0, 200000)
```

![image](https://github.com/user-attachments/assets/f232c833-be9f-4742-b7d9-76b150287ae8)

The axis can be further adjusted as needed.
