### ISSUE TITLE
Dynamic predictor in effect_plot and interact_plot

### ISSUE THREAD

**Issue by haishiro** [jacob-long/jtools#37]
It'd be nice if it were possible to pass in the predictor for effect_plot and interact_plot as a string variable, since one might want to look at the effects of each variable in a model without having to explicitly type out each predictor.

Something like
```
for(var in colnames(df)){
    effect_plot(model,pred=var)
}
```

**Comment by jacob-long** [comment]
I have been thinking about ways I can do what you're suggesting without causing existing code to stop working.

In the meantime, a way around this is to use the functions `make_predictions` and `plot_predictions`, which use standard evaluation — that is, `var` will be evaluated as the string for the column name rather than as `"var"`.

Try this:

```r
for (var in colnames(df)) {
  predictions <- make_predictions(model, pred = var, interval = TRUE)
  plot_predictions(predictions)
}
```

As a side note, you'll either need `interval = TRUE` in the call to `make_predictions` or `interval = FALSE` in the call to `plot_predictions` due to a bug I just found while preparing the answer to your question.

**Comment by haishiro** [comment]
Thanks for the workaround - that works for what I'm doing at the moment.

On trying to implement it without breaking existing code, I've come up with two suggestions:

1. Check the length of pred. It's unlikely that someone is using data with only 1 row, so if the length is 1 then one could assume that the user intends for the predictor to be treated as a string instead of as the bare name.

```R
data(cars)
attach(cars)

# Returns 1
length("speed")

# Returns nrow(cars)
length(speed)

# Returns 1
pred <- "speed"
length(pred)
```

2. Verify that pred actually exists in the model.  I'm not sure how clunky this would be considering each type of model is structured a little bit differently, but you can extract a character vector of term labels used in the model:
```R
# lm
attr(model$terms,"term.labels")
# lmer
attr(attr(model@frame,"terms"),"term.labels")
```
If the parsed pred doesn't exist in this vector, then use pred as a string instead. Could even go one step further and give a warning if both are not found in term labels, since make_predictions will throw an error that is not terribly descriptive when someone attempts to pass in a predictor that doesn't exist.

**Comment by jacob-long** [comment]
Starting in `jtools` version 2.0.0 (commit 667523615f8be107f369a848bed7658e3a1e3809) — which is not yet released but is available in the [`interactions-split`](/jacob-long/jtools/tree/interactions-split) branch — the `pred` arguments are evaluated using [tidy evaluation](https://dplyr.tidyverse.org/articles/programming.html). In interactive use, this won't change anything. 

To use within a function/loop/etc., you just need the "bang bang" syntax that will be familiar for those who have programmed with recent versions of `dplyr`. For instance, this

```r
for (var in colnames(df)) {
    effect_plot(model, pred = !! var)
}
```

will work. The `!!` is exported from the `rlang` package (and `dplyr` and perhaps others) and tells `effect_plot` to treat `var` as a variable to be evaluated rather than the literal name of the column.
