### ISSUE TITLE
summs producing strange characters in Rmarkdown output

### ISSUE THREAD

**Issue by foundinblank** [jacob-long/jtools#47]
Love the `summs()` function and its pretty output in the console! I see this: 

![image](https://user-images.githubusercontent.com/31513760/49963331-896cc780-ff0f-11e8-9992-697d93fd6ef0.png)

But when produced as code output in Rmarkdown html notebooks (using the Preview button), I get this instead: 

![image](https://user-images.githubusercontent.com/31513760/49963351-9a1d3d80-ff0f-11e8-8c96-1d0a8f7701df.png)

How to fix?

**Comment by jacob-long** [comment]
Good question. I'm surprised this happens and I hadn't realized it since I've always used RMarkdown/`knitr` to generate HTML documents rather than the notebooks.

Unfortunately, I don't think there's much I can do about it since I don't know of a way to detect whether the function is being evaluated in an R notebook. This is really a bug on RStudio's end, which they seem to be aware of (rstudio/rstudio#2364) although it looks like it will be a while before it's addressed.

**Comment by jacob-long** [comment]
This was indeed fixed as we hoped.
