### ISSUE TITLE
Rmarkdown pdf does not compile

### ISSUE THREAD

**Issue by nlpaces** [jacob-long/jtools#58]
<
Mac OS; latest versions RStudio/R

Poisson glm model.

Call jtools functions summ() and effect_plot().

All chunks returns expected output in Console.

Knitting to PDF fails.

/Applications/RStudio.app/Contents/MacOS/pandoc/pandoc +RTS -K512m -RTS Enrolled.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output Enrolled.tex --template /Library/Frameworks/R.framework/Versions/3.5/Resources/library/rmarkdown/rmd/latex/default-1.17.0.2.tex --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable 'compact-title:yes' 
output file: Enrolled.knit.md

This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
! Package inputenc Error: Unicode character χ (U+3C7)
(inputenc)                not set up for use with LaTeX.

Try other LaTeX engines instead (e.g., xelatex) if you are using pdflatex. For R Markdown users, see https://bookdown.org/yihui/rmarkdown/pdf-document.html
Error: Failed to compile Enrolled.tex. See https://yihui.name/tinytex/r/#debugging for debugging tips. See Enrolled.log for more info.
Execution halted

Have done all suggested debugging
[Enrolled.Rmd.txt](https://github.com/jacob-long/jtools/files/3100905/Enrolled.Rmd.txt)

Knitting successful to MS word.

If chunks with jtools function calls set to eval = F, PDF compiles.

Data files attached.

.Rmd file attached in txt format.

Nathan
[ForNathanFig1eligible_20190418.xlsx](https://github.com/jacob-long/jtools/files/3100896/ForNathanFig1eligible_20190418.xlsx)
[ForNathanFig1enrolled_20190418.xlsx](https://github.com/jacob-long/jtools/files/3100897/ForNathanFig1enrolled_20190418.xlsx)

[Enrolled.Rmd.txt](https://github.com/jacob-long/jtools/files/3100903/Enrolled.Rmd.txt)

**Comment by jacob-long** [comment]
Thanks a lot for including all of this info to help me. 

This is an interesting problem and bear in mind that I'm troubleshooting on Windows. I can't quite replicate the error. I can't get it to compile even if I drop all the `jtools` stuff. Interestingly, when I set `keep_tex = TRUE` in the YAML header, I can compile the `.tex` file it produces.

Since there's probably some weird Windows stuff going on with my machine, I wonder what kind of TeX output you're getting. Can you change the relevant part of the YAML header to include this:

```
output:
  pdf_document: 
    keep_tex: true
```

instead of this

```
output: 
  pdf_document: default
```

And then send me the `.tex` that it creates?
