### ISSUE TITLE
Question: Are the odds ratio CIs in `summ()` calculated correctly?

### ISSUE THREAD

**Issue by jimvine** [jacob-long/jtools#99]
It is my understanding that confidence intervals on odds ratios cannot be calculated by simply taking the `exp()` of the default CI (see, e.g. [1], [2]).

Looking at the source, I see:

``` {r}
  if (exp == TRUE) {

    ecoefs <- exp(coefs)
    lci <- exp(coefs - (ses * tcrit))
    uci <- exp(coefs + (ses * tcrit))
```

This looks to me like it's just wrapping `exp()` around the same formula that the function uses to calculate the default CIs.

I'm not sure whether there is something else going on elsewhere in the code that is making these CIs correct.

[1] https://stackoverflow.com/a/33098344/4957167
[2] https://www.andrewheiss.com/blog/2016/04/25/convert-logistic-regression-standard-errors-to-odds-ratios-with-r/

**Comment by jacob-long** [comment]
Yeah, I think you've got this right.

`exp()` on the coefficients: no problem
`exp()` on the SEs: bad

So I calculate the the confidence intervals, *then* exponentiate so they can be asymmetrical as they should be. I wasn't aware of there being some exponentiated-equivalent version of the SE and to be honest I don't know how we'd interpret it — that's why I just drop the SEs from the output when `exp = TRUE`.
